HELP_TOPICS = {
    'features': [
        '=== CALC FEATURES ===',
        '',
        '-- Syntax --',
        '  2+2            Add',
        '  10-3           Subtract',
        '  4*5            Multiply',
        '  10/3           Divide',
        '  10%3           Modulo',
        '  2^10           Power',
        '  5!             Factorial (postfix)',
        '  2pi            Implicit multiply',
        '  (2+3)(4+5)     Implicit multiply',
        '',
        '-- Comparisons --',
        '  5 > 3          Returns 1 (true)',
        '  5 < 3          Returns 0 (false)',
        '  5 == 5         Equal',
        '  5 != 3         Not equal',
        '  5 >= 5         Greater or equal',
        '  3 <= 4         Less or equal',
        '',
        '-- Fractions --',
        '  1/2 + 1/3 = 5/6',
        '  Mixed fractions: 5/2 -> 2 1/2',
        '  Toggle: Ctrl+D',
        '',
        '-- Percentage --',
        '  50%            = 0.5',
        '  25% * 200      = 50',
        '  Ctrl+M inserts %',
        '',
        '-- Scientific Notation --',
        '  1e6            = 1000000',
        '  2.5e-3         = 0.0025',
    ],
    'functions': [
        '=== FUNCTIONS ===',
        '',
        '-- Trigonometry --',
        '  sin(30)        Sine (degrees)',
        '  cos(60)        Cosine',
        '  tan(45)        Tangent',
        '  asin(0.5)      Inverse sine',
        '  acos(0.5)      Inverse cosine',
        '  atan(1)        Inverse tangent',
        '  atan2(y,x)     2-arg inverse tan',
        '',
        '-- Hyperbolic --',
        '  sinh(1)        Hyperbolic sine',
        '  cosh(1)        Hyperbolic cosine',
        '  tanh(1)        Hyperbolic tangent',
        '  asinh(1)       Inv hyperbolic sin',
        '  acosh(1)       Inv hyperbolic cos',
        '  atanh(0.5)     Inv hyperbolic tan',
        '',
        '-- Logarithms --',
        '  log(100)       Log base 10',
        '  log(8,2)       Log base 2',
        '  log2(8)        Log base 2',
        '  ln(2.718)      Natural log',
        '  exp(1)         e^x',
        '',
        '-- Roots & Powers --',
        '  sqrt(16)       Square root',
        '  cbrt(8)        Cube root',
        '  pow(2,10)      Power function',
        '',
        '-- Rounding --',
        '  floor(3.7)     Round down',
        '  ceil(3.2)      Round up',
        '  round(3.5)     Round to nearest',
        '  abs(-5)        Absolute value',
        '  sign(-3)       -1, 0, or 1',
        '',
        '-- Combinatorics --',
        '  fact(5)        Factorial (or 5!)',
        '  nPr(5,2)       Permutations',
        '  nCr(5,2)       Combinations',
        '',
        '-- Statistics --',
        '  mean(1,2,3)    Average',
        '  stddev(1,2,3)  Sample std dev',
        '',
        '-- Utilities --',
        '  min(3,1,4)     Smallest value',
        '  max(3,1,4)     Largest value',
        '  gcd(12,8)      Greatest common div',
        '  lcm(4,6)       Least common mult',
        '  clamp(x,lo,hi) Clamp to range',
        '  hypot(3,4)     Hypotenuse (5)',
        '  mod(10,3)      Modulo',
        '',
        '-- Random --',
        '  rand()         0 to 1',
        '  rand(10)       0 to 10',
        '  randint(1,6)   Integer 1 to 6',
    ],
    'constants': [
        '=== CONSTANTS ===',
        '',
        '  pi    3.14159265...',
        '  e     2.71828182...',
        '  phi   1.61803398...  (golden ratio)',
        '  g     9.80665        (gravity m/s2)',
        '  c     299792458      (speed of light)',
        '',
        'Use in expressions:',
        '  2*pi*r          Circle circumference',
        '  e^x             Exponential',
        '  phi^2 = phi+1   Golden ratio identity',
    ],
    'memory': [
        '=== MEMORY & VARIABLES ===',
        '',
        '-- Store & Recall --',
        '  A=5            Store 5 in A',
        '  A              Recall A',
        '  X=2*pi*3       Store formula',
        '',
        '-- Available Variables --',
        '  A, B, C        First three',
        '  D, E, F        Next three',
        '  X, Y, M        Extra variables',
        '  Ans            Last result',
        '',
        'All variables persist across',
        'calculator sessions.',
    ],
    'fractions': [
        '=== FRACTIONS ===',
        '',
        'Just use a/b notation:',
        '  1/2 + 1/3',
        '  = 5/6',
        '',
        '  3/4 * 2/5',
        '  = 6/20 = 3/10',
        '',
        '  1/2 + 1/4',
        '  = 3/4',
        '',
        'Mix with decimals:',
        '  0.5 + 1/4',
        '  = 0.75',
        '',
        'Mixed fractions display:',
        '  5/2  ->  2 1/2',
        '  7/4  ->  1 3/4',
        '  -5/2 -> -2 1/2',
        '',
        'Toggle fraction mode: Ctrl+D',
    ],
    'percentage': [
        '=== PERCENTAGE ===',
        '',
        'Use % to divide by 100:',
        '  50%    = 0.5',
        '  25%    = 0.25',
        '  100%   = 1',
        '',
        'Use in expressions:',
        '  50% * 200',
        '  = 0.5 * 200 = 100',
        '',
        '  200 + 10% * 200',
        '  = 200 + 20 = 220',
        '',
        '  200 * 15%',
        '  = 200 * 0.15 = 30',
        '',
        'Shortcut: Ctrl+M inserts %',
    ],
    'power': [
        '=== EXPONENTS ===',
        '',
        'Syntax: x^y or x**y',
        '',
        '  2^10      = 1024',
        '  3^2       = 9',
        '  9^0.5     = 3',
        '  (1/2)^-1  = 2',
        '',
        'Chained power (left-to-right):',
        '  2^3^2 = 2^9 = 512',
        '',
        'Negative exponents:',
        '  2^-3 = 1/8 = 0.125',
    ],
    'sqrt': [
        '=== SQUARE ROOTS ===',
        '',
        'Syntax: sqrt(x) or x^(1/2)',
        '',
        '  sqrt(16)  = 4',
        '  sqrt(2)   = 1.41421...',
        '  sqrt(0.25)= 0.5',
        '',
        'Cube root: cbrt(x)',
        '  cbrt(27) = 3',
        '',
        'Any root: x^(1/n)',
        '  16^(1/4) = 2',
    ],
    'trig': [
        '=== TRIGONOMETRY ===',
        '',
        '-- Basic --',
        '  sin(30)   = 0.5',
        '  cos(60)   = 0.5',
        '  tan(45)   = 1',
        '',
        '-- Inverse --',
        '  asin(0.5) = 30',
        '  acos(0.5) = 60',
        '  atan(1)   = 45',
        '',
        '-- Hyperbolic --',
        '  sinh(1)   = 1.17520',
        '  cosh(1)   = 1.54308',
        '  tanh(1)   = 0.76159',
        '',
        'Angle modes: DEG, RAD, GRAD',
        'Check with: Ctrl+D in calc',
    ],
    'calculus': [
        '=== CALCULUS ===',
        '',
        '-- Derivatives --',
        '  diff(x^n, x) = n*x^(n-1)',
        '  diff(sin(x), x) = cos(x)',
        '  diff(cos(x), x) = -sin(x)',
        '  diff(e^x, x) = e^x',
        '  diff(ln(x), x) = 1/x',
        '',
        '-- Integrals --',
        '  int(x^n, x) = x^(n+1)/(n+1)',
        '  int(sin(x), x) = -cos(x)',
        '  int(e^x, x) = e^x',
        '  int(1/x, x) = ln(x)',
        '',
        '-- Limits --',
        '  lim(x->0) sin(x)/x = 1',
        '  lim(x->inf) 1/x = 0',
        '',
        'Use antiderivative method:',
        '  F(b) - F(a) for definite',
    ],
    'cas': [
        '=== CAS (ALGEBRA) ===',
        '',
        '-- Symbolic Simplify --',
        '  x + x = 2x',
        '  2*x + 3*x = 5x',
        '  1*x = x',
        '  x^0 = 1, x^1 = x',
        '',
        '-- Differentiation --',
        '  diff(x^3, x) = 3x^2',
        '  diff(sin(x), x) = cos(x)',
        '  diff(e^(2x), x) = 2e^(2x)',
        '',
        '-- Integration --',
        '  int(x^2, x) = x^3/3',
        '  int(cos(x), x) = sin(x)',
        '  int(1/x, x) = ln(x)',
        '',
        '-- Equation Solving --',
        '  solve(2x+3=7, x) = 2',
        '  solve(x^2-4=0, x) = 2, -2',
        '  solve(x^2+x-6=0, x) = 2, -3',
        '',
        '-- Expand --',
        '  expand((x+1)(x+2))',
        '  = x^2+3x+2',
        '',
        '-- Factor --',
        '  factor(x^2+3x+2)',
        '  = (x+1)(x+2)',
        '  factor(x^2-4)',
        '  = (x-2)(x+2)',
        '',
        '-- Bare equations auto-solve --',
        '  2x+3=7 -> x=2',
        '  x^2-4=0 -> x=2,-2',
        '',
        '-- CAS Mode Toggle --',
        '  Ctrl+C toggles CAS on/off',
        '  When OFF: pure numeric calc',
    ],
    'shortcuts': [
        '=== CALC SHORTCUTS ===',
        '',
        '-- Input Shortcuts --',
        '  Ctrl+F         Insert fraction',
        '  Ctrl+E         Insert exponent',
        '  Ctrl+B         Insert sqrt',
        '  Ctrl+I         Insert integral',
        '  Ctrl+S         Insert sum',
        '  Ctrl+D         Toggle frac/decimal',
        '  Ctrl+R         Insert subscript',
        '  Ctrl+L         Insert limit / clear',
        '  Ctrl+M         Insert percentage (%)',
        '  Ctrl+G         Graph on OLED',
        '  Ctrl+U         Toggle CAS mode',
        '  Ctrl+X         Exit and save',
        '',
        '-- Navigation --',
        '  Tab            Next field',
        '  Enter          Evaluate',
        '  Up/Down        History nav',
        '  Left/Right     Move cursor',
        '  Esc            Clear input',
        '  Backspace      Delete char',
    ],
    'complex': [
        '=== COMPLEX NUMBERS ===',
        '',
        '-- Notation --',
        '  3+4i           Complex number',
        '  i              Imaginary unit',
        '  2i             Pure imaginary',
        '',
        '-- Arithmetic --',
        '  (3+4i)+(1-2i)  Addition',
        '  (3+4i)*(1-2i)  Multiplication',
        '  (3+4i)/(1+i)   Division',
        '  (2+3i)^2       Power',
        '',
        '-- Functions --',
        '  re(3+4i)       Real part = 3',
        '  im(3+4i)       Imaginary part = 4',
        '  conj(3+4i)     Conjugate = 3-4i',
        '  abs(3+4i)      Modulus = 5',
        '  arg(1+i)       Argument (rad)',
        '  sqrt(-1)       = i',
        '  exp(i*pi)       = -1',
    ],
    'matrix': [
        '=== MATRICES ===',
        '',
        '-- Syntax --',
        '  [1,2;3,4]      2x2 matrix',
        '  [1,2,3;4,5,6]  2x3 matrix',
        '',
        '-- Arithmetic --',
        '  A+B             Matrix add',
        '  A*B             Matrix multiply',
        '  3*A             Scalar multiply',
        '  A/B             A * inv(B)',
        '',
        '-- Functions --',
        '  det([1,2;3,4])  Determinant',
        '  inv([1,2;3,4])  Inverse',
        '  tr([1,2;3,4])   Trace',
        '  transpose(A)    Transpose',
        '  rref(A)         Reduced row echelon',
        '  eye(3)          3x3 identity',
        '  zeros(2,3)      2x3 zero matrix',
    ],
    'regression': [
        '=== REGRESSION & LISTS ===',
        '',
        '-- List Syntax --',
        '  L1={1,2,3,4}   Assign list',
        '  L1              Recall list',
        '',
        '-- List Functions --',
        '  length(L1)      List length',
        '  sum(L1)         Sum of elements',
        '  sort(L1)        Sorted list',
        '  mean(L1)        Average',
        '  stddev(L1)      Sample std dev',
        '',
        '-- Regression --',
        '  linreg(L1,L2)   Linear: y=mx+b',
        '  quadreg(L1,L2)  Quadratic: y=ax^2+bx+c',
        '  expreg(L1,L2)   Exponential: y=a*e^(bx)',
        '  logreg(L1,L2)   Logarithmic: y=a+b*ln(x)',
        '  pwreg(L1,L2)    Power: y=a*x^b',
        '  MedMed(L1,L2)   Median-median line',
        '  corr(L1,L2)     Correlation coefficient',
    ],
    'numerical': [
        '=== NUMERICAL METHODS ===',
        '',
        '-- Summation/Product --',
        '  summate(x^2, x, 1, 10)',
        '    Sum x^2 from x=1 to 10',
        '  product(x, x, 1, 5)',
        '    Product x from 1 to 5',
        '',
        '-- Integration/Differentiation --',
        '  fnInt(x^2, x, 0, 1)',
        '    Numerical integral 0 to 1',
        '  fnDiff(x^2, x, 3)',
        '    Derivative at x=3',
        '',
        '-- Sequences --',
        '  seq(x^2, x, 1, 5)',
        '    = {1, 4, 9, 16, 25}',
    ],
    'distributions': [
        '=== STATISTICAL DISTRIBUTIONS ===',
        '',
        '-- Normal --',
        '  normalpdf(x, mu, sigma)',
        '  normalcdf(a, b, mu, sigma)',
        '  invNorm(p, mu, sigma)',
        '',
        '-- Binomial --',
        '  binompdf(n, p, x)',
        '  binomcdf(n, p, x)',
        '',
        '-- Poisson --',
        '  poissonpdf(lambda, x)',
        '  poissoncdf(lambda, x)',
        '',
        '-- t / Chi-sq / F --',
        '  tcdf(a, b, df)',
        '  χ²cdf(a, b, df)',
        '  fcdf(a, b, df1, df2)',
        '',
        '-- Tests --',
        '  ztest(mu0, sigma, xbar, n)',
        '  ttest(mu0, s, xbar, n)',
    ],
    'systems': [
        '=== SYSTEMS & PIECEWISE ===',
        '',
        '-- System Solver --',
        '  solve2(x+y-5, x-y-1, 0, 0)',
        '    Newton method for 2x2',
        '    Returns {x: 3.0, y: 2.0}',
        '',
        '-- Piecewise --',
        '  when(5>3, 10, 20)',
        '    Returns 10 (true branch)',
        '  piecewise(x, x>0, x, -x)',
        '    Absolute value function',
    ],
}

HELP_TOPIC_LIST = sorted(HELP_TOPICS.keys())
